Address pullrequest issues
Pull request conversation: https://github.com/pbrisbin/aurget/pull/62

main issue: https://github.com/pbrisbin/aurget/issues/41

diff --git a/aurget b/aurget
--- a/aurget
+++ b/aurget
@@ -175,15 +175,13 @@ resolving() { $resolve_dependencies; }
 eager_sudo() { $eager_sudo; }
 
 create_package_directory() {
-  if [ -d "$pkgbuild_directory" ]
-  then
-  else
-  mkdir "$pkgbuild_directory" || die 'unable to create package directory' 
+  if [[ ! -d $cache_directory ]]; then
+  mkdir "$cache_directory" || die 'unable to create package directory' 
   fi
 }
 
 clean_package_directory() {
-  rm -rf "${pkgbuild_directory:?}"/*
+  rm -rf "${cache_directory:?}"/*
 }
 
 enter_build_directory() {
@@ -342,7 +340,8 @@ set_defaults() {
   silent=false
   sort_mode='name'
   sync_mode='install'
-  pkgbuild_directory='~/.cache/aurget'
+  cache_directory="${XDG_CACHE_HOME:-$HOME/.cache}/aurget"
+  temp_directory="/tmp/aurget"
   user_config="${XDG_CONFIG_HOME:-$HOME/.config}/aurgetrc"
 
   EDITOR="${EDITOR:-$VISUAL}"
@@ -513,8 +512,10 @@ resolve() {
 }
 
 source_pkgbuild() {
-  local name="$1" pkgbuild="$pkgbuild_directory/${1}_PKGBUILD"
-
+  local name="$1" pkgbuild="$temp_directory/${1}_PKGBUILD"
+rpc_info "$@" 
+mv $tmp_directory/${1}_PKGBUILD $cache/$name/$version/PKGBUILD
+pkgbuild="$cache/$name/$version/PKGBUILD"
   if [[ ! -f "$pkgbuild" ]]; then
     if pkgbuild "$name" > "$pkgbuild"; then
       debug "PKGBUILD found for $colorG$name$nocolor"
@@ -565,7 +566,7 @@ setup_targets() {
     version="${versions[$name]}"
 
     if [[ -z "$version" ]]; then
-      pkgbuild="$pkgbuild_directory/${name}_PKGBUILD"
+      pkgbuild="$cache_directory/${name}_PKGBUILD"
 
       if [[ -f "$pkgbuild" ]]; then
         debug "target $colorG$name$nocolor may have moved to repos"
@@ -730,8 +731,8 @@ declare -A target_deps     # pkgbase->is-dep?
 initialize "$@"
 if clean; then
 clean_package_directory
-fi
-if searching; then
+elif
+searching; then
   perform_search
 else
   eager_sudo && sudo_upfront
