Cleaner process_targets(), removed unnecessary traps

diff --git a/aurget b/aurget
--- a/aurget
+++ b/aurget
@@ -619,13 +619,15 @@ setup_targets() {
 
 # process_targets {{{
 process_targets() {
-  Name=
-  Version=
-  URLPath=
-  dep=
-  pkg=
+  Name=''
+  Version=''
+  URLPath=''
+  dep=''
+  pkg=''
+  list_names_len=${#list_names[@]}
+  mk_deps_len=${#mk_deps[@]}
 
-  for ((i=0; i<${#list_names[@]}; i++)); do
+  for ((i=0; i<$list_names_len; i++)); do
     Name="${list_names[i]}"
     Version="${list_versions[i]}"
     URLPath="${list_urls[i]}"
@@ -647,7 +649,7 @@ process_targets() {
   done
 
   # remove make depends
-  if $remove_makedepends && [[ ${#mk_deps[@]} -ne 0 ]]; then
+  if ((remove_makedepends)) && ((mk_deps_len > 0 )); then
     display 'Removing make depends...'
     for mk_dep in ${mk_deps[@]}; do
       pacman --noconfirm -R $mk_dep || warn "unable to remove makedepend $mk_dep"
@@ -663,10 +665,10 @@ set_defaults() {
   discard_sources=true
   dont_discard_devels=true
   resolve_dependencies=false
-  remove_makedepends=false
+  remove_makedepends=1
   devels=false
   noconfirm=false
-  rebuild=false
+  rebuild=1
   asroot=false
   search_mode='search'
 
@@ -777,7 +779,7 @@ parse_options() {
       --popt)        shift; popts+=" $1"                    ;;
       --nocolor)     donocolor=true                         ;;
       --noconfirm)   noconfirm=true                         ;;
-      --rebuild)     rebuild=true                           ;;
+      --rebuild)     rebuild=0                              ;;
       --asroot)      asroot=true                            ;;
       --devel)       devels=true                            ;;
       --deps)        resolve_dependencies=true              ;;
@@ -865,7 +867,7 @@ main() {
     upgrade) upgrade       ;;
     install) setup_targets ;;
     search)  search_aur    ;;
-    *)       message       ;;
+    *)       echo 'aurget requires arguments, see aurget -h' ;;
   esac
 }
 
@@ -906,8 +908,8 @@ EOF
 }
 # }}}
 
-# clean up if we catch signals
-trap 'clean_exit 1' TERM HUP QUIT INT
+# clean up on exit
+trap 'clean_exit 1' EXIT
 
 aur='https://aur.archlinux.org'
 aur_srch="$aur/rpc.php?type=search&arg="
@@ -938,33 +940,25 @@ clean_exit
 # NOT
 # errors=false; if [[ $errors == true ]]; then...; fi
 # 
-# * denotes completion:
-#
-# * 228	  local multiple=false ret=0 url
-# * 234	  [[ ${#args[@]} -gt 1 ]] && multiple=true
-#   506	  while true; do
-#   656	  # just true/false and non-config options
-#   657	  discard_sources=true
-#   658	  dont_discard_devels=true
-#   659	  resolve_dependencies=false
-#   660	  remove_makedepends=false
-#   661	  devels=false
-#   662	  noconfirm=false
-#   663	  rebuild=false
-#   664	  asroot=false
-#   682	  local config _sourced=false
-#   688	    _sourced=true
-#   695	    _sourced=true
-#   701	      _sourced=true
-#   745	  local _opmode='' donocolor=false
-#   772	      --nocolor)     donocolor=true                         ;;
-#   773	      --noconfirm)   noconfirm=true                         ;;
-#   774	      --rebuild)     rebuild=true                           ;;
-#   775	      --asroot)      asroot=true                            ;;
-#   776	      --devel)       devels=true                            ;;
-#   777	      --deps)        resolve_dependencies=true              ;;
-#   778	      --nodeps)      resolve_dependencies=false             ;;
-#   781	      --discard)     discard_sources=true                   ;;
-#   782	      --nodiscard)   discard_sources=false                  ;;
-#   802	  [[ "$sync_mode" != 'install' ]] && resolve_dependencies=false
+#   512	  while true; do
+#   665	  discard_sources=true
+#   666	  dont_discard_devels=true
+#   667	  resolve_dependencies=false
+#   669	  devels=false
+#   670	  noconfirm=false
+#   672	  asroot=false
+#   690	  local config _sourced=false
+#   696	    _sourced=true
+#   703	    _sourced=true
+#   709	      _sourced=true
+#   753	  local _opmode='' donocolor=false
+#   780	      --nocolor)     donocolor=true                         ;;
+#   781	      --noconfirm)   noconfirm=true                         ;;
+#   783	      --asroot)      asroot=true                            ;;
+#   784	      --devel)       devels=true                            ;;
+#   785	      --deps)        resolve_dependencies=true              ;;
+#   786	      --nodeps)      resolve_dependencies=false             ;;
+#   789	      --discard)     discard_sources=true                   ;;
+#   790	      --nodiscard)   discard_sources=false                  ;;
+#   810	  [[ "$sync_mode" != 'install' ]] && resolve_dependencies=false
 # vim:foldmethod=marker foldmarker={{{,}}} ts=2 sw=2 sts=2
